<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libraries\org.Communication\org.Communication.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TouchSocket">
      <HintPath>..\..\..\libs\TouchSocket\TouchSocket.dll</HintPath>
    </Reference>
    <Reference Include="TouchSocket.Core">
      <HintPath>..\..\..\libs\TouchSocket\TouchSocket.Core.dll</HintPath>
    </Reference>
    <Reference Include="TouchSocket.Modbus">
      <HintPath>..\..\..\libs\TouchSocket\TouchSocket.Modbus.dll</HintPath>
    </Reference>
    <Reference Include="TouchSocket.SerialPorts">
      <HintPath>..\..\..\libs\TouchSocket\TouchSocket.SerialPorts.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
